// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package db

import (
	"context"
)

const createOrReplaceGoal = `-- name: CreateOrReplaceGoal :one
INSERT INTO goals (
    scope_id,
    goal_id,
    objective,
    status,
    version,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    1,
    strftime('%s', 'now'),
    strftime('%s', 'now')
)
ON CONFLICT(scope_id) DO UPDATE SET
    goal_id = excluded.goal_id,
    objective = excluded.objective,
    status = excluded.status,
    version = goals.version + 1,
    updated_at = strftime('%s', 'now')
RETURNING scope_id, goal_id, objective, status, version, created_at, updated_at
`

type CreateOrReplaceGoalParams struct {
	ScopeID   string `json:"scope_id"`
	GoalID    string `json:"goal_id"`
	Objective string `json:"objective"`
	Status    string `json:"status"`
}

func (q *Queries) CreateOrReplaceGoal(ctx context.Context, arg CreateOrReplaceGoalParams) (Goal, error) {
	row := q.queryRow(ctx, q.createOrReplaceGoalStmt, createOrReplaceGoal,
		arg.ScopeID,
		arg.GoalID,
		arg.Objective,
		arg.Status,
	)
	var i Goal
	err := row.Scan(
		&i.ScopeID,
		&i.GoalID,
		&i.Objective,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM goals
WHERE scope_id = ?
`

func (q *Queries) DeleteGoal(ctx context.Context, scopeID string) error {
	_, err := q.exec(ctx, q.deleteGoalStmt, deleteGoal, scopeID)
	return err
}

const getGoalByScopeID = `-- name: GetGoalByScopeID :one
SELECT scope_id, goal_id, objective, status, version, created_at, updated_at
FROM goals
WHERE scope_id = ? LIMIT 1
`

func (q *Queries) GetGoalByScopeID(ctx context.Context, scopeID string) (Goal, error) {
	row := q.queryRow(ctx, q.getGoalByScopeIDStmt, getGoalByScopeID, scopeID)
	var i Goal
	err := row.Scan(
		&i.ScopeID,
		&i.GoalID,
		&i.Objective,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGoalStatus = `-- name: UpdateGoalStatus :one
UPDATE goals
SET
    status = ?,
    updated_at = strftime('%s', 'now')
WHERE scope_id = ? AND goal_id = ?
RETURNING scope_id, goal_id, objective, status, version, created_at, updated_at
`

type UpdateGoalStatusParams struct {
	Status  string `json:"status"`
	ScopeID string `json:"scope_id"`
	GoalID  string `json:"goal_id"`
}

func (q *Queries) UpdateGoalStatus(ctx context.Context, arg UpdateGoalStatusParams) (Goal, error) {
	row := q.queryRow(ctx, q.updateGoalStatusStmt, updateGoalStatus, arg.Status, arg.ScopeID, arg.GoalID)
	var i Goal
	err := row.Scan(
		&i.ScopeID,
		&i.GoalID,
		&i.Objective,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
