// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package db

import (
	"context"
)

const accumulateActiveTime = `-- name: AccumulateActiveTime :exec
UPDATE goals
SET
    active_seconds = active_seconds + (strftime('%s', 'now') - updated_at),
    updated_at = strftime('%s', 'now')
WHERE session_id = ? AND status = 'active'
`

func (q *Queries) AccumulateActiveTime(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.accumulateActiveTimeStmt, accumulateActiveTime, sessionID)
	return err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (
    session_id,
    goal_id,
    objective,
    status,
    created_at,
    updated_at,
    active_seconds
) VALUES (
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now'),
    0
)
RETURNING session_id, goal_id, objective, status, created_at, updated_at, active_seconds
`

type CreateGoalParams struct {
	SessionID   string `json:"session_id"`
	GoalID    string `json:"goal_id"`
	Objective string `json:"objective"`
	Status    string `json:"status"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.queryRow(ctx, q.createGoalStmt, createGoal,
		arg.SessionID,
		arg.GoalID,
		arg.Objective,
		arg.Status,
	)
	var i Goal
	err := row.Scan(
		&i.SessionID,
		&i.GoalID,
		&i.Objective,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveSeconds,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM goals
WHERE session_id = ?
`

func (q *Queries) DeleteGoal(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteGoalStmt, deleteGoal, sessionID)
	return err
}

const getGoalBySessionID = `-- name: GetGoalBySessionID :one
SELECT session_id, goal_id, objective, status, created_at, updated_at, active_seconds
FROM goals
WHERE session_id = ? LIMIT 1
`

func (q *Queries) GetGoalBySessionID(ctx context.Context, sessionID string) (Goal, error) {
	row := q.queryRow(ctx, q.getGoalBySessionIDStmt, getGoalBySessionID, sessionID)
	var i Goal
	err := row.Scan(
		&i.SessionID,
		&i.GoalID,
		&i.Objective,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveSeconds,
	)
	return i, err
}

const updateGoalStatus = `-- name: UpdateGoalStatus :one
UPDATE goals
SET
    status = ?,
    updated_at = strftime('%s', 'now')
WHERE session_id = ? AND goal_id = ?
RETURNING session_id, goal_id, objective, status, created_at, updated_at, active_seconds
`

type UpdateGoalStatusParams struct {
	Status  string `json:"status"`
	SessionID string `json:"session_id"`
	GoalID  string `json:"goal_id"`
}

func (q *Queries) UpdateGoalStatus(ctx context.Context, arg UpdateGoalStatusParams) (Goal, error) {
	row := q.queryRow(ctx, q.updateGoalStatusStmt, updateGoalStatus, arg.Status, arg.SessionID, arg.GoalID)
	var i Goal
	err := row.Scan(
		&i.SessionID,
		&i.GoalID,
		&i.Objective,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveSeconds,
	)
	return i, err
}
