// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_disabled.sql

package db

import (
	"context"
)

const deleteMCPDisabledServer = `-- name: DeleteMCPDisabledServer :exec
DELETE FROM mcp_disabled_servers WHERE name = ?
`

func (q *Queries) DeleteMCPDisabledServer(ctx context.Context, name string) error {
	_, err := q.exec(ctx, q.deleteMCPDisabledServerStmt, deleteMCPDisabledServer, name)
	return err
}

const insertMCPDisabledServer = `-- name: InsertMCPDisabledServer :exec
INSERT OR IGNORE INTO mcp_disabled_servers (name) VALUES (?)
`

func (q *Queries) InsertMCPDisabledServer(ctx context.Context, name string) error {
	_, err := q.exec(ctx, q.insertMCPDisabledServerStmt, insertMCPDisabledServer, name)
	return err
}

const listMCPDisabledServers = `-- name: ListMCPDisabledServers :many
SELECT name FROM mcp_disabled_servers ORDER BY name
`

func (q *Queries) ListMCPDisabledServers(ctx context.Context) ([]string, error) {
	rows, err := q.query(ctx, q.listMCPDisabledServersStmt, listMCPDisabledServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
