// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_enabled.sql

package db

import (
	"context"
)

const deleteMCPEnabledServer = `-- name: DeleteMCPEnabledServer :exec
DELETE FROM mcp_enabled_servers WHERE name = ?
`

func (q *Queries) DeleteMCPEnabledServer(ctx context.Context, name string) error {
	_, err := q.exec(ctx, q.deleteMCPEnabledServerStmt, deleteMCPEnabledServer, name)
	return err
}

const insertMCPEnabledServer = `-- name: InsertMCPEnabledServer :exec
INSERT OR IGNORE INTO mcp_enabled_servers (name) VALUES (?)
`

func (q *Queries) InsertMCPEnabledServer(ctx context.Context, name string) error {
	_, err := q.exec(ctx, q.insertMCPEnabledServerStmt, insertMCPEnabledServer, name)
	return err
}

const listMCPEnabledServers = `-- name: ListMCPEnabledServers :many
SELECT name FROM mcp_enabled_servers ORDER BY name
`

func (q *Queries) ListMCPEnabledServers(ctx context.Context) ([]string, error) {
	rows, err := q.query(ctx, q.listMCPEnabledServersStmt, listMCPEnabledServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
